#!/usr/bin/perl
#Author: Sajeed Mohammad Shahriat 
#Affiliation: Rochester Institute of Technology (RIT)
#All rights reserved-2017 The materials are open source and can be re-used and modified, given that the copyright headers in this file is NOT removed.

#this script will generate a output file with the text as defined

use strict;
use warnings;

my $filename = 'report.txt';
open (my $fh, '>', $filename) or die "Could not open file '$filename' $!";
print $fh "My first report generated by perl\n";
close $fh;
print "done\n";

#endcode
